version: '3.3'
services:
  web:
    image: tautiz/web4study
    volumes:
      - ./laravel_file:/var/www/html/
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      APACHE_SERVER_NAME: laravel.local
      APPLICATION_ENV: development
      APACHE_DOCUMENT_ROOT: /var/www/html/public

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - myapp:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass

  node:
    image: "node:8"
    user: "node"
    working_dir: /var/www/html/
    environment:
      - NODE_ENV=production
    volumes:
      - ./laravel_filai:/var/www/html/
    expose:
      - "8081"
    command:
    - "npn install"

volumes:
  myapp:
    external: false